### ISSUE TITLE
Link to guide broken in humble-video/humble-video-demos

### ISSUE THREAD

**Issue by sidmishraw** [artclarke/humble-video#114]
The link to **Overly Simplistic Guide to Internet Video** in the [demo section](https://github.com/artclarke/humble-video/tree/master/humble-video-demos) is broken.

An updated link would be really helpful 😃

**Comment by rkosegi** [comment]
@sidmishraw You can try [web archive snapshot](http://web.archive.org/web/20160314115333/http://blog.xuggle.com:80/2009/01/23/overly-simplistic-guide-to-internet-video/)

**Comment by sidmishraw** [comment]
Well, the videos are missing 😞
