### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by jared2501** [artclarke/humble-video#117]
Hey @artclarke - any chance you could release 0.3.0?

**Comment by mufumbo** [comment]
+1

**Comment by kpodvolecky** [comment]
+1

**Comment by TimYi** [comment]
@artclarke I'm a java developer. I want to do a screen supervise program recently. I found humble-video, looked at the demos, and it seems perfect to me.
I think this project is great, it's former project xuggle-xuggler is also greate, the concepts are clear, the apis are easy to use and understand.

**Comment by artclarke** [comment]
Should show up on Maven Central within the next 24-hours. Just waiting for it to sync.
