### ISSUE TITLE
DecodeAndPlayVideo does not continue past first frame

### ISSUE THREAD

**Issue by Tank-Missile** [artclarke/humble-video#125]
The example code renders the first frame, but does not render the frames following it.

EDIT: I should clarify that I ran the demo on linux. My friend tested the same code on his windows machine and the video moved, although it stopped prematurely. By lowering the system time, I was able to get the video to move on my machine. It seems the timings are a bit screwy depending on the operating system. I'll need to use a more sophisticated player, as you mentioned in the comments.

**Comment by artclarke** [comment]
What version are you using?

**Comment by Tank-Missile** [comment]
0.3.0. Currently, I'm trying to get audio and video to play at the same time frame, but the audio causes the video to stutter. This occurs when the play method is called on rawAudio, since the audio takes longer to play than the video frame takes to display. From looking at the examples, it seems I have to manually keep the video and audio in sync somehow.

**Comment by artclarke** [comment]
yeah, see https://github.com/artclarke/humble-video/issues/135.
