### ISSUE TITLE
0.3.0 slower than 0.2.1?

### ISSUE THREAD

**Issue by dannyZhou** [artclarke/humble-video#127]
GeneratedVideoLength: 200s
FrameRate: 30fps

Same codes, using 
```
        <dependency>
            <groupId>io.humble</groupId>
            <artifactId>humble-video-all</artifactId>
            <version>0.3.0</version>
        </dependency>
```
Takes 70s to render a mp4 file.

Using 
```
        <dependency>
            <groupId>io.humble</groupId>
            <artifactId>humble-video-all</artifactId>
            <version>0.2.1</version>
        </dependency>
```
Takes 26s.

Why?

**Comment by artclarke** [comment]
Without an example program or file it's really impossible to tell. But 

HumbleVideo 0.2.0: Uses FFmpeg 2.4
HumbleVideo 0.3.0 Uses FFmpeg 2.6

Otherwise it's essentially the same, so my guess is some difference between FFmpeg versions and libx264 versions.
