### ISSUE TITLE
Height not divisible by 2 (1920x975)

### ISSUE THREAD

**Issue by neomatrix369** [artclarke/humble-video#128]
I get this when an app using humble-video tries to run on a resolution with an odd screen height:

```
[libx264 @ 00000000003DB9A0] height not divisible by 2 (1920x975)
```

What is a way around it, could we not make the code check for this and fall back to either an acceptable resolution or round up or round down the value of height.

Any other workaround this error?

**Comment by artclarke** [comment]
This is a constraint of the libx264 encoding library and therefore not something we can work around :(
