### ISSUE TITLE
Invalid data found when processing input (-1094995529)

### ISSUE THREAD

**Issue by Tank-Missile** [artclarke/humble-video#129]
I'm hoping you can help diagnose this issue with a personal project I'm working on, as it's either a bug on your end, or something I'm missing on mine. What exactly is needed to serialize packets, send them over the network, and de-serialize them on the other end? The MediaPacket class has a bunch of setters, so I started by storing the data needed to set them in a serializable class. I also serialized the data from the decoders. Let me make it clear that I am getting both the packet data and decoder data across the network, and I even got audio packets to play remotely. However, the audio works inconsistently, and frequently causes crashes. Trying to decode a video packet results in the exception "Invalid data found when processing input (-1094995529)".

**Comment by flynn-buc** [comment]
Did you ever resolve this?

**Comment by Tank-Missile** [comment]
Unfortunatley no. To be honest, I probably should have used ffmpeg instead of making my life more difficult with a straight UDP library. [It has streaming built right into it](https://trac.ffmpeg.org/wiki/StreamingGuide).

**Comment by flynn-buc** [comment]
Thanks ! I was looking at ffmpeg as well. I'll probably use that instead
