### ISSUE TITLE
Projects dependent on version 0.2.0 fail to build without access to snapshot repo

### ISSUE THREAD

**Issue by djabry** [artclarke/humble-video#49]
https://github.com/artclarke/humble-video/blob/master/humble-video-parent/pom.xml#L11 points to 0.2.0-SNAPSHOT version of modules. 

My build succeeds when this is changed to 0.2.0

**Comment by artclarke** [comment]
Yikes; sorry about that. Will hot fix as 0.2.1.

**Comment by artclarke** [comment]
Fixed in commit 2e274657e879b20387756c54db24318d26c8f080, and now tagged as version 0.2.1
