### ISSUE TITLE
Demuxer hangs bug

### ISSUE THREAD

**Issue by eix128** [artclarke/humble-video#55]
Hello , when i try to run application with : 
Demuxer demuxer = Demuxer.make(); // <= the program hangs at this command.
I looked the dump.

sometimes it freezes on
package io.humble.ferry;
function
unpackLibrary

**Comment by aligokalppeker** [comment]
That actually also happened on me,

In a x64 JVM, humble-video tries to load x86 dll's and fails to load, this may be a reason for hanging state. Also size of the native jars are quite big, that may result in increased extracting time.

Once, humble-video loads the dll's, it does not hang again...

It is quite a bit problem for me now, I don't know how to fix it. Any work around is  quite wellcome...

**Comment by artclarke** [comment]
Humble tries to guess the OS and bit-width, but doesn't always get it
right, and then defaults into loading each DLL it can find until one
succeeds. So yes, this can lead to long unpack and load times.

Not much can be done about the specific unpacking time for a given library,
but a patch might work to get it to better 'guess' the OS and bitness (32
vs 64). It's in the io.humble.ferry package (all Java code). Patches
appreciate if you guys wanna take a look (see the JNI* classes).

- Art

**Comment by aligokalppeker** [comment]
Bitness detection error happens when multiple JVM is installed in the machine ( x86 and x64 ). When one type of JVM is installed, then the correct dll is loaded. Why dll package size is so high according to the xuggler ?( 25mb vs 100mb )

**Comment by artclarke** [comment]
I just release Humble Video 0.3.0 which tries (through maven) to only pull in the native files for the exact OS and bit-ness you're using. So you may have better luck with that.
