### ISSUE TITLE
Question: Online JavaDocs and EIA-608 Teletext in MPEG2TS ATSC Video

### ISSUE THREAD

**Issue by EvanBoucher** [artclarke/humble-video#63]
Hello,

I am experimenting with this library and I have a few questions. I have included the maven central jars in my Java project and I have them working. So far, I am impressed! :+1: Thanks!

My first question is about the JavaDocs for this library. I see that a lot of the source code is documented, but I cannot access the JavaDocs within Eclipse and I am unable to find them anywhere online. Is there a way to access the JavaDocs for this library?

My next question refers to the input video format of ATSC OTA TV video and Close Captioning.
My setup is that I am receiving a MPEG2TS stream over UDP and I need to decode and display the video and audio. I am using the demos on this repository (very helpful! thank you!) for decoding and playing Audio and also using the similar video demo. I run each demo separately, so I am only decoding the video or audio one at a time currently. I am able to get the video demo to decode the UDP stream over the network with little issues (it will crash overtime typically due to "Invalid data found when processing input (-1094995529)."  The video will display in the Java window, but the Close Captioning data is not present. For ATSC video, the Close Captioning stream is within the video stream (within the user data packet) as defined by the EIA-608 standard. I noticed that the repository source contains references to the EIA-608 Close Captioning standard codec. The current standard is CEA-708, which I cannot find within the Humble-video source (FFMPEG does not appear to have the 708 standard so that adds up).

Here is a helpful wikipedia link to the EIA-608 standard: http://en.wikipedia.org/wiki/EIA-608

Is there a way to decode the MPEGTS video stream to display the encoded Close Captioning?

Thank you so much for your time and help! Please let me know if I can provide any details that would help you.
Sincerely,
Evan

**Comment by artclarke** [comment]
Hi Evan,

If FFMPEG doesn't support the 708 standard, then there's not much I can do
(beyond someone patching FFMPEG). Once that's done, the support for reading
non-audio or non-video packet data in Humble (or Xuggler) is pretty much
non existent :(

- Art

**Comment by EvanBoucher** [comment]
Thanks for the response Art. I will check back with FFMPEG and and see what can be done there.

If I end up doing work on it I will let you know to maybe incorporate it into this library.

Are there any compiled JavaDocs available for this library? Online or otherwise.
Thanks again,
- Evan

**Comment by artclarke** [comment]
They should be uploaded with the maven artifacts?

https://repo1.maven.org/maven2/io/humble/humble-video-all/0.2.1/

See the -javadoc jars. Eclipse should pick them up if you tell the Maven
plugin to also download the javadocs.

- Art

**Comment by EvanBoucher** [comment]
Thanks Art!

My Maven project was not picking up the JavaDoc jar. I will investigate. Likely something I am doing wrong. 

Thank you so much for your help.
Sincerely,
Evan
