### ISSUE TITLE
Crypto "No rule to make target `all'"

### ISSUE THREAD

**Issue by aurelpop** [artclarke/humble-video#67]
I've tried to build humble-video on ubuntu 12.04 LTS but I get some errors from Openssl/Crypto:

[INFO] --- exec-maven-plugin:1.2.1:exec (exec-three) @ humble-video-captive ---
Making all in zlib
make[1]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/zlib'
Incarcerated package configured: /home/humble-video/humble-video-captive/src/main/gnu/zlib
Incarcerating package /home/humble-video/humble-video-captive/src/main/gnu/zlib to fake DESTDIR=
Incarceration complete: /home/humble-video/humble-video-captive/src/main/gnu/zlib
make[1]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/zlib'
Making all in libvpx
make[1]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/libvpx'
Incarcerated package configured: /home/humble-video/humble-video-captive/src/main/gnu/libvpx
Incarcerating package /home/humble-video/humble-video-captive/src/main/gnu/libvpx to fake DESTDIR=
make[2]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/libvpx/csrc'
make[2]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/libvpx/csrc'
Incarceration complete: /home/humble-video/humble-video-captive/src/main/gnu/libvpx
make[1]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/libvpx'
Making all in openssl
make[1]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl'
Incarcerated package configured: /home/humble-video/humble-video-captive/src/main/gnu/openssl
Incarcerating package /home/humble-video/humble-video-captive/src/main/gnu/openssl to fake DESTDIR=
Out of date files; re-running make
make[2]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl/csrc'
making all in crypto...
make[3]: Entering directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl/csrc/crypto'
make[3]: *** No rule to make target `all'.  Stop.
make[3]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl/csrc/crypto'
make[2]: *** [build_crypto] Error 1
make[2]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl/csrc'
make[1]: Leaving directory `/home/humble-video/humble-video-captive/target/native/i686-pc-linux-gnu6/openssl'
make[1]: *** [all-local] Error 2
make: *** [all-recursive] Error 1

The exact steps:
-> fresh Ubuntu 12.02 LTS
-> After that:
$ apt-get install git
$ apt-get install yasm
$ apt-get install gcc
$ apt-get install g++-multilib
$ apt-get install make
$ apt-get install pkg-config
$ apt-get install valgrind
$ apt-get install graphviz [for DOT]
$ apt-get install doxygen
$ apt-get install python-software-properties
$ apt-get install autotools-dev
$ apt-get install automake
$ apt-get install build-essential libtool
$ apt-get install libpcre3 libpcre3-dev
$ apt-get install byacc

// INSTALL JDK
$ add-apt-repository ppa:webupd8team/java
$ apt-get update
$ apt-get install oracle-java8-installer
$ update-alternatives --config java  [OPTIONAL - has no effect if there is only one java version installed]
$ update-alternatives --config javac [OPTIONAL - has no effect if there is only one java version installed]
$ nano /etc/environment [Append: {New Line}JAVA_HOME="/usr/lib/jvm/java-8-oracle"]
$ source /etc/environment

$ apt-get install maven

// INSTALL humble-swig
$ cd /home
$ git clone https://github.com/artclarke/humble-swig.git
$ cd humble-swig
$ ./autogen.sh
$ ./configure
$ make
$ make install

// INSTALL humble-video
$ cd /home
$ git clone https://github.com/artclarke/humble-video.git
$ cd humble-video
$ mvn install

After a few minutes I get the above error.
Did I do something wrong? Did I miss something?

Hope someone can help me. I've just spent 6 hours on this, trying to add/remove files, edit Makefile, disable md2 etc and nothing works.

**Comment by chrishan** [comment]
Here is how I fixed this error:
1. download and unzip http://www.openssl.org/source/openssl-1.0.1j.tar.gz to openssl-1.0.1j/
2. replace humble-video/humble-video-captive/src/main/gnu/openssl/csrc/* with openssl-1.0.1j/
3. clean the previous build with ```(cd humble-video-stage && mvn clean) && mvn clean```
3. run ```mvn install``` again

**Comment by chrishan** [comment]
I have this problem as well. Turn out it was because I was using Xcode 6.3 which have problems compiling ffmepg. I downgraded to Xcode 6.1.1 and replaced humble-video/humble-video-captive/src/main/gnu/openssl/csrc/* with [openssl-1.0.1j](http://www.openssl.org/source/openssl-1.0.1j.tar.gz). Finally the build was successful. [Here are the detailed steps](https://github.com/chrishan/humble-video/blob/master/README.md#mac-os-x-notes).

**Comment by jamestalmage** [comment]
@chrishan's fix worked for me.
Upgrade to 6.1.1 (I was on 5.3), and replace the openssl `csrc` folder.

I was on OS X Yosemite, so I also had to instal valgrind this way:
```
brew install --HEAD valgrind
```

@artclarke It would be good to incorporate @chrishan's changes to the docs (or just update with the latest sources).
