### ISSUE TITLE
JVM Crash due to thrown native exception

### ISSUE THREAD

**Issue by aligokalppeker** [artclarke/humble-video#88]
I use "Demuxer" to open a ".ts" container. But during the execution, invalid data stream causes HumbleVideo to throw a ffmpegexception : "could not queryStreamMetaData on XXXXX".

It is okay to throw the exception but the problem is, i can not catch that exception in JVM side and later on JVM crashes. I am not sure but JVM crash may be due to reading from Demuxer in invalid state(code may assume that it is opened...).

Is there any way to catch these type of native exceptions to avoid performing further operations on invalid Demuxer instance?

Thanks.

**Comment by aligokalppeker** [comment]
This is a crucial situation, is there any one to help? Especially @artclarke can you help me ?

**Comment by artclarke** [comment]
Without sample code reproducing the problem (with sample media) there isn't much I can do here.
