### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005)

### ISSUE THREAD

**Issue by borjaevo** [artclarke/humble-video#90]
Exception access violation when trying to transcode from some formats like MJPEG packed on AVI. 
# Problematic frame:
# C  [ntdll.dll+0x2a981]

io.humble.video.VideoJNI.Encoder_encode(JLio/humble/video/Encoder;JLio/humble/video/MediaPacket;JLio/humble/video/MediaSampled;)V+0

I attached the log

I tried to convert from other formats to h264 and is working well. 

[hs_err_pid12204.txt](https://github.com/artclarke/humble-video/files/127987/hs_err_pid12204.txt)

**Comment by artclarke** [comment]
Without sample code reproducing the issue there's not much I can do here...

note though... this is a VERY low priority hobby for me right now, so even if you add an example, I'm not sure I'll get to it anytime soon.
