### ISSUE TITLE
JVM Warning on disabling stack guard

### ISSUE THREAD

**Issue by jprabawa** [artclarke/humble-video#91]
Hi,

Im using version 0.2.1 in a tomcat app and am seeing this warning:

Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library .../apache-tomcat-7.0.40/temp/humble2140094587474468185.tmp which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

Why is this happening and is this a benign issue?

Thanks,

J

**Comment by nmpgaspar** [comment]
I'm facing the same issue, could someone shed some light on how to solve this?

**Comment by artclarke** [comment]
It's happening because in OpenJDK7 it gives that warning when we attempt to load a libhumble.so that doesn't match the same bit-width (i.e. 32bit or 64bit) of the JVM you are using. To get around, change your dependences to depend on `humble-video-noarch.jar` and then the specific `humble-video-arch...` POM that you run on.

**Comment by nmpgaspar** [comment]
I'm running Ubuntu 16.04, I changed my pom accordingly, 

<dependency>
      <groupId>io.humble</groupId>
      <artifactId>humble-video-noarch</artifactId>
      <version>0.2.1</version>
    </dependency>
    <dependency>
      <groupId>io.humble</groupId>
      <artifactId>humble-video-arch-x86_64-pc-linux-gnu6</artifactId>
      <version>0.2.1</version>
    </dependency>

Yet, I'm still getting this:
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /tmp/humble6716513183841428352.tmp which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.

Any idea what I might be doing wrong?
