### ISSUE TITLE
is art clarke dead ?

### ISSUE THREAD

**Issue by aligokalppeker** [artclarke/humble-video#93]
I see that @artclarke, for a while, does not response to the any of the reported issues nor does update repo for any release. ffmpeg 3.0 released, many feedback has been given, many actions should have been triggered @artclarke for any update for the humble-video. In the end, humble-video is his son :)

So the issue is that : Is @artclarke dead ?

**Comment by PaulBGD** [comment]
According to his LinkedIn, he began a new job a few months after he stopped working on humble-video.
https://www.linkedin.com/in/ArtClarke

**Comment by cqjjjzr** [comment]
No.
He updated the project several months ago, so I believe he's still alive :)

**Comment by artclarke** [comment]
Alive, but day job takes priority. Still, closing this issue.
