### ISSUE TITLE
Demuxer rtmp problem -1094995529

### ISSUE THREAD

**Issue by maniladev** [artclarke/humble-video#94]
I try to open demuxer to read from rtmp.

demuxer = Demuxer.make();
demuxer.open("rtmp://mydomain.com/rtmp/temp" null, false, true, null, null);

I get:  
Exception in thread "main" java.lang.RuntimeException: Error opening url: rtmp://mydomain.com/rtmp/temp; : Invalid data found when processing input (-1094995529)

Searching the String -1094995529 it seems the error is about the audio codec.  Any clue how to work around?

**Comment by jahorner** [comment]
How did you resolve this issue?  I'm running into the same problem.

**Comment by jtanul** [comment]
It is sensitive to what server you are using.  Previously my server is nginx with rtmp module. I switched to crtmpd and it was ok.
